# MS Data Analysis Tools

## Load Data

**Input:**
-   `.tsv` file obtained as an output of `preprocessing_template.ipynb`

In [8]:
%matplotlib inline

import pandas as pd
from MSprocessing.stats.utils import split_data, within_group_corr, within_between_corr, group_table
from MSprocessing.stats.plots import volcano_plot, plot_heatmap, plot_venn
from MSprocessing.stats.ttests import run_dea
from MSprocessing.stats.models import run_linear_model
from MSprocessing.stats.enrichment import go_enrichment, convert_ids

In [4]:
index_cols = ["label_id", "group", "AL_kode", "plate_position", "plate_nr",
 "sample_name", "sample_type", "study_ID", "timepoint", "sample_order"]

data = pd.read_csv("preprocessed_data.tsv", sep="\t", index_col=index_cols)
data = data[data.index.get_level_values("sample_type") == "sample"].copy()

In [5]:
proteome, meta = split_data(data, "sample_name") #set column to use as index
proteome

,protein_count,A0A075B6H9,A0A075B6I9,A0A075B6J1,A0A075B6J2,A0A075B6J9,A0A075B6K0,A0A075B6K2,A0A075B6K4,A0A075B6K5,...,Q9Y608,Q9Y613,Q9Y624,Q9Y646,Q9Y696,Q9Y6C2,Q9Y6E0,Q9Y6N7,Q9Y6R7,Q9Y6Z7
sample_name,,,,,,,,,,,,,,,,,,,,,
plate1_A6,975,17.947,24.628,18.982,18.334,24.092,22.504,17.066,25.475,27.176,...,16.897,17.451,19.557,15.698,16.294,13.903,18.166,13.810,22.882,21.943
plate1_A7,852,19.876,28.156,19.648,19.660,24.761,23.565,20.618,25.316,27.186,...,17.031,16.734,19.096,15.076,17.157,13.677,16.622,13.354,22.378,22.870
plate1_A8,877,18.540,27.113,21.213,20.693,24.542,23.909,19.014,26.534,28.187,...,16.700,16.773,18.911,15.744,16.962,13.367,17.117,13.658,22.241,21.892
plate1_A9,943,21.397,27.437,20.206,19.579,24.991,25.077,19.243,24.648,28.477,...,15.732,16.835,19.426,15.903,17.255,12.519,17.700,12.984,23.891,22.215
plate1_A10,947,18.763,26.929,21.612,19.869,23.846,24.752,19.764,24.478,27.560,...,16.238,16.754,19.973,16.147,17.221,13.430,17.840,13.275,22.783,22.652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
plate2_E10,883,19.783,27.749,20.546,18.747,25.028,24.144,19.837,24.796,27.532,...,17.150,16.995,18.269,16.554,16.662,12.965,17.061,13.224,22.071,22.747
plate2_E11,884,17.130,27.648,19.989,19.296,23.870,25.375,21.014,26.807,27.672,...,17.317,17.225,19.509,15.996,17.133,13.324,17.015,13.305,23.452,23.616
plate2_E12,894,17.555,27.484,22.941,18.930,24.228,24.956,18.630,25.497,27.774,...,18.431,16.858,17.811,15.544,17.102,13.476,17.552,13.000,25.178,23.668
plate2_F1,846,18.351,26.589,19.841,19.533,25.172,26.008,19.510,27.216,29.526,...,16.746,16.435,19.752,15.703,16.985,13.679,17.436,13.975,21.710,22.347
plate2_F2,824,19.291,27.178,19.850,20.200,24.145,24.816,19.042,26.634,27.635,...,16.605,17.084,19.420,17.064,16.815,14.123,17.729,13.879,22.459,23.866

In [6]:
meta

,label_id,group,AL_kode,plate_position,plate_nr,sample_type,study_ID,timepoint,sample_order
sample_name,,,,,,,,,
plate1_A6,4083906373,Intervention,100005,A6,plate1,sample,67.0,day_15,1
plate1_A7,4083918930,Intervention,100006,A7,plate1,sample,34.0,day_0,2
plate1_A8,4083982663,Intervention,100007,A8,plate1,sample,63.0,day_0,3
plate1_A9,4083907917,Control,100008,A9,plate1,sample,16.0,day_15,4
plate1_A10,4083985725,Intervention,100009,A10,plate1,sample,79.0,day_0,5
...,...,...,...,...,...,...,...,...,...
plate2_E10,4083996660,Control,100153,E10,plate2,sample,57.0,day_0,148
plate2_E11,4083980445,Intervention,100154,E11,plate2,sample,79.0,day_15,149
plate2_E12,4083966190,Intervention,100155,E12,plate2,sample,35.0,day_15,150
plate2_F1,4083947093,Control,100156,F1,plate2,sample,45.0,day_15,151
plate2_F2,4083966929,Intervention,100157,F2,plate2,sample,5.0,day_0,152

In [ ]:
# make a table to analyze the statistics for each group (eg. gender, age, etc.)
table = group_table(
    meta,
    group=["group"],
    summary_cols=["plate_nr", "timepoint"],
    stat="median",
    q=(0.25, 0.75),
)

table

C:\Users\aben0177\Documents\git_projects\MSprocessing\MSprocessing\stats\utils.py:274: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  subset = grouped.get_group(keys if len(group) > 1 else keys[0])
C:\Users\aben0177\Documents\git_projects\MSprocessing\MSprocessing\stats\utils.py:274: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  subset = grouped.get_group(keys if len(group) > 1 else keys[0])

,group,N,plate_nr,timepoint
0,Control,73 (49.3%),"plate1 (64.4%), plate2 (35.6%)","day_15 (50.7%), day_0 (49.3%)"
1,Intervention,75 (50.7%),"plate1 (56.0%), plate2 (44.0%)","day_15 (49.3%), day_0 (50.7%)"

### Exploratory Analysis

In [8]:
plot_heatmap(
    proteome, 
    meta, 
    group_by=["study_ID", "group"]
    )

In [9]:
#calculate the correlation between samples of the same group and with samples outside of the group

corr_ext = within_between_corr(proteome, meta, id_col="study_ID", method="pearson")
print(f"Mean within-patient corr:  {corr_ext['within_mean']:.3f}")
print(f"Mean between-patient corr: {corr_ext['between_mean']:.3f}")

Mean within-patient corr:  -0.021
Mean between-patient corr: -0.006

### Differential Expression Analysis

In [10]:
meta

,label_id,group,AL_kode,plate_position,plate_nr,sample_type,study_ID,timepoint,sample_order
sample_name,,,,,,,,,
plate1_A6,4083906373,Intervention,100005,A6,plate1,sample,67.0,day_15,1
plate1_A7,4083918930,Intervention,100006,A7,plate1,sample,34.0,day_0,2
plate1_A8,4083982663,Intervention,100007,A8,plate1,sample,63.0,day_0,3
plate1_A9,4083907917,Control,100008,A9,plate1,sample,16.0,day_15,4
plate1_A10,4083985725,Intervention,100009,A10,plate1,sample,79.0,day_0,5
...,...,...,...,...,...,...,...,...,...
plate2_E10,4083996660,Control,100153,E10,plate2,sample,57.0,day_0,148
plate2_E11,4083980445,Intervention,100154,E11,plate2,sample,79.0,day_15,149
plate2_E12,4083966190,Intervention,100155,E12,plate2,sample,35.0,day_15,150
plate2_F1,4083947093,Control,100156,F1,plate2,sample,45.0,day_15,151
plate2_F2,4083966929,Intervention,100157,F2,plate2,sample,5.0,day_0,152

In [20]:
dea_results = run_dea(
    proteome=proteome,
    meta=meta,
    group_col="group",
    group1="Intervention",
    group2="Control",
    adjust="stepdown_perm",
    n_perm=10000,
    method="student_ttest",
)

dea_results

              log2fc      pval      padj
protein
A0A0C4DH32 -0.457200  0.000787  0.000700
Q14247     -0.419894  0.001068  0.001800
P02745      0.356462  0.004370  0.012299
P62834     -0.333084  0.009275  0.035796
P00338      0.228261  0.010926  0.054495
...              ...       ...       ...
Q13094      0.000383  0.997467  1.000000
P32004      0.000196  0.998308  1.000000
Q9HCN6      0.000217  0.998447  1.000000
Q5SQ64     -0.000102  0.999184  1.000000
Q96PD5     -0.000084  0.999428  1.000000

[1273 rows x 3 columns]

In [22]:
print(dea_results.loc["Q14247"])
print(dea_results.loc["A0A087WSY6"])
print(dea_results.loc["Q96BM9;Q9NVJ2"])

log2fc   -0.419894
pval      0.001068
padj      0.001800
Name: Q14247, dtype: float64
log2fc   -0.218402
pval      0.145025
padj      1.000000
Name: A0A087WSY6, dtype: float64
log2fc    0.139359
pval      0.048982
padj      0.880012
Name: Q96BM9;Q9NVJ2, dtype: float64

In [21]:
volcano_plot(dea_results, alpha=0.05, labels = False)

In [23]:
convert_ids(dea_results, from_type="uniprot", to_type="symbol").head(4)

WARNING	Task(Task-2) biothings.client:iteration.py:concatenate_list()- Input sequence provided is already in string format. No operation performed
WARNING	Task(Task-2) biothings.client:iteration.py:concatenate_list()- Input sequence provided is already in string format. No operation performed
INFO	Task(Task-2) biothings.client:base.py:_repeated_query()- querying 1-1000 ...
INFO	Task(Task-2) biothings.client:base.py:_repeated_query()- querying 1001-1273 ...
INFO	Task(Task-2) biothings.client:base.py:_querymany()- Finished.
WARNING	Task(Task-2) biothings.client:base.py:_querymany()- 11 input query terms found dup hits:	[('P04908', 2), ('P62805', 10), ('P59665', 2), ('P0DP23', 3), ('P0DMV8', 2), ('P84243', 2), ('P0C0L5
WARNING	Task(Task-2) biothings.client:base.py:_querymany()- 114 input query terms found no hit:	['A0A0C4DH32', 'P0DOY2', 'P01877', 'P01700', 'A0A075B6R2', 'A0A0C4DH39', 'A0A0C4DH30', 'A0A0C4DH35',
INFO	Task(Task-2) biothings.client:base.py:_querymany()- Pass "returnall=True" to return complete lists of duplicate or missing query terms.

              log2fc      pval      padj
A0A0C4DH32 -0.457200  0.000787  0.000700
CTTN       -0.419894  0.001068  0.001800
C1QA        0.356462  0.004370  0.012299
RAP1A      -0.333084  0.009275  0.035796

### Mixed LM

In [ ]:
lmm_results = run_linear_model(
    proteome, 
    meta, 
    formula="y ~ timepoint", 
    group_col="study_ID", 
    adjust="fdr_bh", 
    reml=True,
    filter_to="timepoint"
    )

lmm_results

Defaulted to OLS for A0A075B6S5
Defaulted to OLS for A0A0C4DH34
Defaulted to OLS for A0A0C4DH72
Defaulted to OLS for A0A0J9YX35
Defaulted to OLS for A0M8Q6
Defaulted to OLS for O15394
Defaulted to OLS for O43184
Defaulted to OLS for O43294
Defaulted to OLS for P01137
Defaulted to OLS for P02655
Defaulted to OLS for P05387
Defaulted to OLS for P08238
Defaulted to OLS for P08670
Defaulted to OLS for P08833
Defaulted to OLS for P11277
Defaulted to OLS for P11465
Defaulted to OLS for P11586
Defaulted to OLS for P13501
Defaulted to OLS for P13598
Defaulted to OLS for P13639
Defaulted to OLS for P13647
Defaulted to OLS for P13688
Defaulted to OLS for P15907
Defaulted to OLS for P21980
Defaulted to OLS for P22314
Defaulted to OLS for P23142
Defaulted to OLS for P23368
Defaulted to OLS for P25705
Defaulted to OLS for P27918
Defaulted to OLS for P29622
Defaulted to OLS for P34932
Defaulted to OLS for P48735
Defaulted to OLS for P51149
Defaulted to OLS for P63241;Q6IS14;Q9GZV4
Defaulted to OLS for P80108
Defaulted to OLS for P84243
Defaulted to OLS for Q00013
Defaulted to OLS for Q05639
Defaulted to OLS for Q13232
Defaulted to OLS for Q13421
Defaulted to OLS for Q14520
Defaulted to OLS for Q15691
Defaulted to OLS for Q16557
Defaulted to OLS for Q16851
Defaulted to OLS for Q5JSH3
Defaulted to OLS for Q8TF42
Defaulted to OLS for Q9BXR6
Defaulted to OLS for Q9HCB6
Defaulted to OLS for Q9HCL0
Defaulted to OLS for Q9NQW7
Defaulted to OLS for Q9P0L0
Defaulted to OLS for Q9UBG0
Defaulted to OLS for Q9UQ74

                coef      pval      padj
protein
P01130     -0.375829  0.013974  0.742675
P27918      0.286729  0.017330  0.742675
Q16851      0.257457  0.019876  0.742675
Q96DR8     -0.213343  0.021031  0.742675
A0A0C4DH72  0.320071  0.022236  0.742675
...              ...       ...       ...
Q9HCB6      0.002943  0.975451  0.994560
Q93088     -0.001929  0.982176  0.994560
Q13232      0.001600  0.985813  0.994560
A0A0C4DH38 -0.001000  0.994274  0.994560
P22314     -0.000771  0.994560  0.994560

[167 rows x 3 columns]

## GO Enrichment

In [26]:
enrichment_ttest = go_enrichment(dea_results, restrict_background=True, adjust="fdr")
enrichment_ttest

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents
0,GO:CC,GO:0005602,complement component C1 complex,0.079232,False,"""A protein complex composed of six subunits of...",2,4,1,1255,0.25,0.500000,query_1,"[GO:0005576, GO:0032991]"
1,GO:CC,GO:0062167,complement component C1q complex,0.079232,False,"""A protein-containing complex composed of six ...",2,4,1,1255,0.25,0.500000,query_1,"[GO:0005576, GO:0032991]"
2,GO:CC,GO:0008076,voltage-gated potassium channel complex,0.079232,False,"""A protein complex that forms a transmembrane ...",2,4,1,1255,0.25,0.500000,query_1,"[GO:0034705, GO:0098797]"
3,GO:CC,GO:0032045,guanyl-nucleotide exchange factor complex,0.079232,False,"""A protein complex that stimulates the exchang...",1,4,1,1255,0.25,1.000000,query_1,[GO:0140535]
4,GO:CC,GO:0034705,potassium channel complex,0.079232,False,"""An ion channel complex through which potassiu...",2,4,1,1255,0.25,0.500000,query_1,[GO:0034703]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,GO:CC,GO:0043226,organelle,0.985318,False,"""Organized structure of distinctive morphology...",1016,4,2,1255,0.50,0.001969,query_1,[GO:0110165]
622,GO:CC,GO:0043227,membrane-bounded organelle,0.985318,False,"""Organized structure of distinctive morphology...",972,4,2,1255,0.50,0.002058,query_1,[GO:0043226]
623,GO:CC,GO:0043230,extracellular organelle,0.985318,False,"""Organized structure of distinctive morphology...",655,4,1,1255,0.25,0.001527,query_1,"[GO:0005576, GO:0043226]"
624,GO:CC,GO:1903561,extracellular vesicle,0.985318,False,"""Any vesicle that is part of the extracellular...",655,4,1,1255,0.25,0.001527,query_1,"[GO:0031982, GO:0065010]"
625,GO:CC,GO:0005615,extracellular space,0.991147,False,"""That part of a multicellular organism outside...",869,4,1,1255,0.25,0.001151,query_1,"[GO:0005576, GO:0110165]"